# Generated by Django 4.1.3 on 2022-11-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('cardNumber', models.IntegerField()),
                ('idOfPerson', models.IntegerField()),
            ],
        ),
    ]
